# Site
name: "The Tech Stack . Net"
description: "Sharing my coding experiments"
meta_description: ""
#logo: 'assets/images/logo.png'
#favicon: 'assets/images/logo.png'
baseurl: ''
url: 'http://localhost'
google_analytics: 'UA-115619272-1'
disqus: 'thetechstack-net'
destination: ./docs
permalink: /blog/:year/:month/:day/:title
mailchimp-list: 'https://thetechstack.us7.list-manage.com/subscribe/post?u=1381d872f022743eb338f00a1&amp;id=88d9fceb21'
future: true
twitter_username: 'PradeepK4J'

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: pradeep
      featured: false
      comments: false

# Authors
authors:
  pradeep:
    name: Pradeep Kundarapu
    display_name: Pradeep Kundarapu
    #gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: k.pradeep12@outlook.com
    web: http://thetechstack.net
    twitter: https://twitter.com/PradeepK4J
    description: "Java & Kotlin developer, blogger and tech enthusiast."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/blog/:year/:month/:day/:title'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge