# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Tech Stack Java"
title_separator: "|"
name: "Pradeep Kundarapu"
email: k.pradeep12@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Sharing my coding experiments
baseurl: "/techstackjava" # the subpath of your site, e.g. /blog
url: "https://kpradeep12.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PradeepK4J
github_username:  kpradeep12
search: true
paginate: 9
paginate_path: /page:num/
timezone: America/New_York
permalink: /blog/:year/:month/:day/:title
destination: ./docs

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
locale: "en-US"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      author_profile: false

comments:
  provider: "disqus"
  disqus:
    shortname: "k_pradeep1234"

social:
  type: Person
  links:
    - "https://twitter.com/PradeepK4J"
    - "https://www.linkedin.com/in/pradeepkundarapu"

author:
  name     : "Pradeep Kundarapu"
  avatar   : "/assets/images/author.jpg"
  bio      : "Java developer, blogger and tech enthusiast."
  location : "Somewhere, USA" 
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/PradeepK4J"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kpradeep12"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pradeepkundarapu/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/PradeepK4J"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kpradeep12"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pradeepkundarapu/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
